'use client'

import { useMemo, useState } from 'react'
import Image from 'next/image'
import { ArrowRight, Heart, Menu, Minus, Plus, Search, ShoppingBag, Sparkles, X } from 'lucide-react'

const products = [
  { name: 'Mori Lounge Chair', category: 'Seating', price: 1890, color: 'Natural Oak', image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=900&q=85', badge: 'Bestseller' },
  { name: 'Forma Side Table', category: 'Tables', price: 640, color: 'Smoked Oak', image: 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=900&q=85', badge: 'New' },
  { name: 'Arc Dining Table', category: 'Tables', price: 3200, color: 'Natural Oak', image: 'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=900&q=85', badge: '' },
  { name: 'Noma Linen Sofa', category: 'Seating', price: 4200, color: 'Oat Linen', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=85', badge: 'Made to order' },
]

const categories = [
  { name: 'Seating', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=85' },
  { name: 'Tables', image: 'https://images.unsplash.com/photo-1532372320572-cda25653a26d?auto=format&fit=crop&w=800&q=85' },
  { name: 'Lighting', image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=85' },
]

function formatPrice(price: number) {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(price)
}

export default function AtelierOakStorefront() {
  const [cartOpen, setCartOpen] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const [selectedCategory, setSelectedCategory] = useState('All pieces')
  const [cartCount, setCartCount] = useState(1)
  const [email, setEmail] = useState('')
  const [notice, setNotice] = useState('')

  const filteredProducts = useMemo(() => selectedCategory === 'All pieces' ? products : products.filter((product) => product.category === selectedCategory), [selectedCategory])

  function addToCart(name: string) {
    setCartCount((count) => count + 1)
    setNotice(`${name} added to your bag`)
    setTimeout(() => setNotice(''), 2500)
  }

  return (
    <main className="min-h-screen bg-background text-foreground">
      <div className="border-b border-border bg-foreground px-4 py-2 text-center text-[10px] font-medium uppercase tracking-[0.22em] text-background md:px-6">
        Complimentary white-glove delivery on orders over $2,000
      </div>

      <header className="sticky top-0 z-40 border-b border-border/70 bg-background/90 backdrop-blur-xl">
        <div className="mx-auto flex h-20 max-w-[1400px] items-center justify-between px-5 md:px-10">
          <button aria-label="Open menu" onClick={() => setMenuOpen(true)} className="flex items-center gap-2 text-sm md:hidden"><Menu size={19} /> Menu</button>
          <nav className="hidden items-center gap-7 text-[11px] font-medium uppercase tracking-[0.16em] md:flex">
            <a href="#shop" className="hover:text-accent transition-colors">Shop</a><a href="#story" className="hover:text-accent transition-colors">Our story</a><a href="#journal" className="hover:text-accent transition-colors">Journal</a>
          </nav>
          <a href="#top" className="font-serif text-3xl tracking-[-0.05em] md:absolute md:left-1/2 md:-translate-x-1/2">Atelier Oak</a>
          <div className="flex items-center gap-4 text-[11px] font-medium uppercase tracking-[0.14em]">
            <button aria-label="Search" className="hidden md:block"><Search size={18} strokeWidth={1.5} /></button>
            <button className="hidden md:block hover:text-accent">Account</button>
            <button aria-label="Open shopping bag" onClick={() => setCartOpen(true)} className="flex items-center gap-2"><ShoppingBag size={18} strokeWidth={1.5} /><span className="hidden sm:inline">Bag ({cartCount})</span><span className="sm:hidden">{cartCount}</span></button>
          </div>
        </div>
      </header>

      {menuOpen && <div className="fixed inset-0 z-50 bg-foreground/30 backdrop-blur-sm md:hidden" onClick={() => setMenuOpen(false)}><div className="h-full w-[82%] bg-background p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><span className="font-serif text-2xl">Atelier Oak</span><button aria-label="Close menu" onClick={() => setMenuOpen(false)}><X /></button></div><nav className="mt-16 flex flex-col gap-7 font-serif text-4xl"><a href="#shop" onClick={() => setMenuOpen(false)}>Shop</a><a href="#story" onClick={() => setMenuOpen(false)}>Our story</a><a href="#journal" onClick={() => setMenuOpen(false)}>Journal</a></nav></div></div>}

      <section id="top" className="relative isolate min-h-[680px] overflow-hidden md:min-h-[calc(100vh-108px)]">
        <Image src="/atelier-oak-hero.png" alt="Sculptural oak chair in a sunlit modern interior" fill priority className="object-cover" sizes="100vw" />
        <div className="absolute inset-0 bg-gradient-to-r from-foreground/70 via-foreground/10 to-transparent" />
        <div className="relative flex min-h-[680px] max-w-[1400px] items-end px-5 pb-14 md:min-h-[calc(100vh-108px)] md:px-10 md:pb-20">
          <div className="max-w-xl text-background"><p className="mb-5 text-[11px] font-medium uppercase tracking-[0.25em] text-background/75">Collection 04 — Quiet forms</p><h1 className="font-serif text-6xl leading-[0.94] tracking-[-0.05em] md:text-8xl">Objects with a point of view.</h1><p className="mt-7 max-w-md text-sm leading-6 text-background/80 md:text-base">Furniture made slowly, for rooms that feel like you. Discover considered forms in solid oak, honest linen, and time-honored craft.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#shop" className="inline-flex items-center gap-3 bg-background px-5 py-3 text-xs font-semibold uppercase tracking-[0.15em] text-foreground transition-transform hover:-translate-y-0.5">Shop the collection <ArrowRight size={16} /></a><a href="#story" className="inline-flex items-center gap-3 border border-background/60 px-5 py-3 text-xs font-semibold uppercase tracking-[0.15em] text-background hover:bg-background/10">Our approach</a></div></div>
        </div>
      </section>

      <section className="mx-auto max-w-[1400px] px-5 py-20 md:px-10 md:py-28"><div className="flex items-end justify-between gap-6"><div><p className="eyebrow">Find your material</p><h2 className="mt-3 font-serif text-4xl tracking-[-0.04em] md:text-6xl">Designed to settle in.</h2></div><a href="#shop" className="hidden items-center gap-2 text-xs font-semibold uppercase tracking-[0.15em] md:flex">View all <ArrowRight size={15} /></a></div><div className="mt-10 grid gap-3 md:grid-cols-3">{categories.map((category) => <a href="#shop" key={category.name} className="group relative aspect-[4/5] overflow-hidden bg-secondary"><Image src={category.image} alt={category.name} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 33vw" /><div className="absolute inset-0 bg-gradient-to-t from-foreground/70 to-transparent" /><div className="absolute bottom-5 left-5 flex items-center justify-between right-5 text-background"><span className="font-serif text-3xl">{category.name}</span><ArrowRight className="transition-transform group-hover:translate-x-1" /></div></a>)}</div></section>

      <section id="shop" className="border-y border-border bg-secondary/45"><div className="mx-auto max-w-[1400px] px-5 py-20 md:px-10 md:py-28"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">The edit</p><h2 className="mt-3 font-serif text-4xl tracking-[-0.04em] md:text-6xl">Pieces for living well.</h2></div><div className="flex flex-wrap gap-2">{['All pieces', 'Seating', 'Tables'].map((category) => <button key={category} onClick={() => setSelectedCategory(category)} className={`border px-4 py-2 text-[11px] font-semibold uppercase tracking-[0.13em] transition-colors ${selectedCategory === category ? 'border-foreground bg-foreground text-background' : 'border-border bg-background hover:border-foreground'}`}>{category}</button>)}</div></div><div className="mt-10 grid gap-x-4 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{filteredProducts.map((product) => <article key={product.name} className="group"><div className="relative aspect-[4/5] overflow-hidden bg-background"><Image src={product.image} alt={product.name} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width: 640px) 50vw, (max-width: 1024px) 25vw, 280px" /><button aria-label={`Add ${product.name} to wishlist`} className="absolute right-3 top-3 flex h-9 w-9 items-center justify-center bg-background/85 backdrop-blur-sm"><Heart size={16} strokeWidth={1.5} /></button>{product.badge && <span className="absolute bottom-3 left-3 bg-background px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.14em]">{product.badge}</span>}</div><div className="pt-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-serif text-xl">{product.name}</h3><p className="mt-1 text-xs text-muted-foreground">{product.color}</p></div><p className="text-sm font-medium">{formatPrice(product.price)}</p></div><button onClick={() => addToCart(product.name)} className="mt-4 flex w-full items-center justify-center gap-2 border border-foreground py-3 text-[10px] font-semibold uppercase tracking-[0.15em] opacity-0 transition-all group-hover:opacity-100 hover:bg-foreground hover:text-background">Add to bag <Plus size={14} /></button></div></article>)}</div></div></section>

      <section id="story" className="mx-auto grid max-w-[1400px] gap-10 px-5 py-20 md:grid-cols-2 md:items-center md:gap-20 md:px-10 md:py-32"><div className="relative aspect-[4/5] overflow-hidden bg-secondary"><Image src="https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=85" alt="Warm oak interior with thoughtfully placed furniture" fill className="object-cover" sizes="(max-width: 768px) 100vw, 50vw" /></div><div className="max-w-lg"><p className="eyebrow">Why Atelier Oak</p><h2 className="mt-4 font-serif text-5xl leading-[1] tracking-[-0.05em] md:text-7xl">The beauty of less, made better.</h2><p className="mt-8 text-base leading-7 text-muted-foreground">We work with a small network of makers who believe the best objects are given time. Every piece is designed in our Copenhagen studio, then finished by hand in workshops across Europe.</p><div className="mt-10 grid grid-cols-2 gap-6 border-y border-border py-6"><div><Sparkles size={18} strokeWidth={1.3} /><p className="mt-3 text-sm font-medium">Thoughtful materials</p><p className="mt-1 text-xs leading-5 text-muted-foreground">FSC-certified oak, natural fibers, and finishes that age beautifully.</p></div><div><span className="font-serif text-2xl">01</span><p className="mt-3 text-sm font-medium">Made to last</p><p className="mt-1 text-xs leading-5 text-muted-foreground">A considered approach to form, function, and a smaller footprint.</p></div></div><a href="#journal" className="mt-8 inline-flex items-center gap-3 text-xs font-semibold uppercase tracking-[0.15em]">Read our story <ArrowRight size={15} /></a></div></section>

      <section id="journal" className="bg-foreground px-5 py-20 text-background md:px-10 md:py-28"><div className="mx-auto max-w-[1400px]"><div className="flex items-end justify-between"><div><p className="eyebrow text-background/60">From the journal</p><h2 className="mt-3 font-serif text-4xl tracking-[-0.04em] md:text-6xl">A slower point of view.</h2></div><span className="hidden font-serif text-2xl md:block">@atelieroak</span></div><div className="mt-12 grid gap-4 md:grid-cols-3"><article className="group"><div className="relative aspect-[1.2] overflow-hidden"><Image src="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85" alt="Quiet living room detail" fill className="object-cover transition duration-700 group-hover:scale-105" sizes="33vw" /></div><p className="mt-5 text-[10px] uppercase tracking-[0.18em] text-background/55">Spaces</p><h3 className="mt-2 font-serif text-2xl">A room with room to breathe</h3></article><article className="group"><div className="relative aspect-[1.2] overflow-hidden"><Image src="https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=900&q=85" alt="Woodworking detail" fill className="object-cover transition duration-700 group-hover:scale-105" sizes="33vw" /></div><p className="mt-5 text-[10px] uppercase tracking-[0.18em] text-background/55">Making</p><h3 className="mt-2 font-serif text-2xl">The grain tells the story</h3></article><article className="group"><div className="relative aspect-[1.2] overflow-hidden"><Image src="https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=900&q=85" alt="Natural materials and fabric" fill className="object-cover transition duration-700 group-hover:scale-105" sizes="33vw" /></div><p className="mt-5 text-[10px] uppercase tracking-[0.18em] text-background/55">Materials</p><h3 className="mt-2 font-serif text-2xl">In praise of natural things</h3></article></div></div></section>

      <section className="border-b border-border bg-accent px-5 py-20 md:px-10 md:py-24"><div className="mx-auto flex max-w-3xl flex-col items-center text-center"><p className="eyebrow">Stay a while</p><h2 className="mt-4 font-serif text-4xl tracking-[-0.04em] md:text-6xl">Good things, thoughtfully sent.</h2><p className="mt-5 max-w-md text-sm leading-6 text-muted-foreground">Join our list for new collections, studio notes, and the occasional thing worth knowing.</p><form onSubmit={(event) => { event.preventDefault(); setEmail(''); setNotice('You’re on the list — welcome in.'); setTimeout(() => setNotice(''), 2500) }} className="mt-8 flex w-full max-w-md border-b border-foreground/50 pb-2"><label htmlFor="email" className="sr-only">Email address</label><input id="email" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Your email address" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground" /><button className="text-xs font-semibold uppercase tracking-[0.15em]">Subscribe <ArrowRight className="ml-2 inline" size={14} /></button></form></div></section>

      <footer className="bg-background px-5 py-10 md:px-10"><div className="mx-auto flex max-w-[1400px] flex-col gap-10 md:flex-row md:items-start md:justify-between"><div><a href="#top" className="font-serif text-3xl tracking-[-0.05em]">Atelier Oak</a><p className="mt-3 max-w-xs text-xs leading-5 text-muted-foreground">Crafted for modern living.<br />Designed in Copenhagen. Made for everywhere.</p></div><div className="grid grid-cols-2 gap-x-16 gap-y-3 text-xs text-muted-foreground"><a href="#shop" className="hover:text-foreground">Shop all</a><a href="#story" className="hover:text-foreground">Our story</a><a href="#journal" className="hover:text-foreground">Journal</a><a href="#top" className="hover:text-foreground">Shipping & returns</a><a href="#top" className="hover:text-foreground">Contact</a><a href="#top" className="hover:text-foreground">Instagram</a></div></div><div className="mx-auto mt-14 flex max-w-[1400px] justify-between border-t border-border pt-5 text-[10px] uppercase tracking-[0.15em] text-muted-foreground"><span>© 2026 Atelier Oak</span><span>Made with intention</span></div></footer>

      {cartOpen && <div className="fixed inset-0 z-50 bg-foreground/25 backdrop-blur-sm" onClick={() => setCartOpen(false)}><aside className="ml-auto flex h-full w-full max-w-md flex-col bg-background p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between border-b border-border pb-5"><div><p className="eyebrow">Your selection</p><h2 className="mt-1 font-serif text-3xl">Shopping bag</h2></div><button aria-label="Close shopping bag" onClick={() => setCartOpen(false)}><X /></button></div><div className="flex flex-1 flex-col justify-center text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-secondary"><ShoppingBag size={24} strokeWidth={1.3} /></div><p className="mt-5 font-serif text-2xl">Mori Lounge Chair</p><p className="mt-1 text-sm text-muted-foreground">Natural Oak · {formatPrice(1890)}</p><div className="mx-auto mt-5 flex items-center gap-5 border border-border px-3 py-2"><button aria-label="Decrease quantity" onClick={() => setCartCount((count) => Math.max(1, count - 1))}><Minus size={14} /></button><span className="text-sm">{cartCount}</span><button aria-label="Increase quantity" onClick={() => setCartCount((count) => count + 1)}><Plus size={14} /></button></div></div><div className="border-t border-border pt-5"><div className="flex justify-between text-sm"><span>Subtotal</span><strong>{formatPrice(1890 * cartCount)}</strong></div><p className="mt-2 text-xs text-muted-foreground">Shipping and taxes calculated at checkout.</p><button className="mt-5 w-full bg-foreground py-4 text-xs font-semibold uppercase tracking-[0.16em] text-background hover:opacity-90">Checkout</button></div></aside></div>}
      {notice && <div role="status" className="fixed bottom-5 left-1/2 z-[60] -translate-x-1/2 bg-foreground px-5 py-3 text-xs font-medium text-background shadow-xl">{notice}</div>}
    </main>
  )
}
